version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./public_html/:/var/www/html/
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
    container_name: apache
  mysql:
    image: mysql:${MYSQL_VERSION}    
    volumes:
      - ./mysql/:/var/lib/mysql/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=itlab
    container_name: mysql
